export const GET_TODOS = 'GET_TODOS';
export const CREATE_TODOS = 'CREATE_TODOS';
export const UPDATE_TODOS = 'UPDATE_TODOS';
export const DELETE_TODOS = 'DELETE_TODOS';
export const CURRENT_TODO = 'CURRENT_TODO';
export const CLEAR_CURRENT_TODO = 'CLEAR_CURRENT_TODO';
export const GET_TODOS_ERROR = 'GET_TODOS_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
